USE master
GO
IF NOT EXISTS (
 SELECT name
 FROM sys.databases
 WHERE name = N'DSTRAINING'
)
 CREATE DATABASE [DSTRAINING];
GO
IF SERVERPROPERTY('ProductVersion') > '12'
 ALTER DATABASE [DSTRAINING] SET QUERY_STORE=ON;
GO